--- 
- hosts: localhost
  name: Deploy Microshift on "{{ provider }}"
  gather_facts: false
  vars:
    provider: libvirt
    ssh_pub: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ssh_priv_path: "~/.ssh/id_rsa"
    default_hostname: true
    hcloud_token: "{{ lookup('env','HCLOUD_TOKEN') }}"
    tf_state: present
    microshift_version: 4.8.0-0.microshift-2022-04-20-182108
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: ../kubeconfig
  tasks:

    - include_tasks: "tasks/preflight.yml"
      when: tf_state == "present"
    
    - include_tasks: "tasks/{{ provider }}.yml"

    - include_tasks: "tasks/fetch_auth.yml"
      when: tf_state == "present"
    
    - include_tasks: "tasks/day2.yml"
      when: tf_state == "present"
