apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-deployment
  namespace: okd-console
  labels:
    app: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - name: console-app
        image: quay.io/openshift/origin-console:4.8
        env:
        - name: BRIDGE_USER_AUTH
          value: disabled
        - name: BRIDGE_K8S_MODE
          value: off-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: https://142.132.187.236.nip.io:6443
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true"
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: console-token-6bpft
              key: token
---
kind: Service
apiVersion: v1
metadata:
  name: console-np-service
  namespace: okd-console
spec:
  selector:
    app: console
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
