variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqFw3NAAKOXod7CX7CJ4fw/4yLtWtYDNI34wzMpZyyfXhJGqf3aLJXNc+hQtdq1H8U6cXTLOF2b8vORqhTME1HejpU1lGip/2uTdM/YoF/YnKBhS+gUAcV7VqjOYW3BfibFwWRoK/2tB76G2QHaTu4n/SzZ3eYrze1d534R0Px05iVq4lGTZos4KBy6fYLXOKVR7fQdHmcootwEz+FNaU4jXUc52XjpAHmETdazX6mNKjW3PqnR3V2H6khodUIJRDzXORpVwpjXzPtoy7NL7Y31d1GYEreLtE3OORQiVDVBY7aAwt/mhytNgFqBbzFIrx4hTLO0SsZ36ZX//vhka3UHEHF9iDFxzJ54xBJj3CZ4CTnMwzRoELIOtQ6FH8lP0gKmlQ0XvmsWSiexHhXA87sBE7TAIQCfyEoXUuBHE3IrMzoiBfZECKQEtdBBEIEaMI2pwSvRgNOoBAuHT2V3JJL2b8TvrFj2hRrvf4nDkL3EP81rC/YxigJFWo5VXE0GaU= root@fedora-2gb-nbg1-1
systemd:
  units:
    - name: microshift.service
      enabled: true
      contents: |
        [Unit]
        Description=Podman container-microshift.service
        Documentation=man:podman-generate-systemd(1)
        After=microshift-init.service
        RequiresMountsFor=/run/containers/storage

        [Service]
        Environment=PODMAN_SYSTEMD_UNIT=%n
        Restart=on-failure
        TimeoutStopSec=70
        ExecStartPre=setsebool -P container_manage_cgroup true
        ExecStart=/usr/bin/podman start microshift
        ExecStop=/usr/bin/podman stop -t 10 microshift
        ExecStopPost=/usr/bin/podman stop -t 10 microshift
        Type=forking

        [Install]
        WantedBy=default.target

    - name: microshift-init.service
      enabled: true
      contents: |
        [Unit]
        Description=Init microshift aio
        Requires=network-online.target systemd-resolved.service

        [Service]
        Type=oneshot
        RemainAfterExit=no
        ExecStart=/bin/sh /etc/containers/microshift_init.sh
        Restart=on-failure

        [Install]
        WantedBy=default.target
storage:
  files:
    - path: /etc/containers/microshift_init.sh
      contents:
        inline: |
          #/bin/bash

          /usr/bin/podman create \
            --name microshift -q --rm -h $(hostname -I| awk '{print $1}').nip.io --privileged \
            -v /lib/modules:/lib/modules -v microshift-data:/var/lib \
            -p 6443:6443 -p 8080:8080 -p 80:80 \
            quay.io/microshift/microshift-aio:4.8.0-0.microshift-2022-04-20-182108
      mode: 0744
      user:
        id: 0
      group:
        id: 0
